export const menuItems = [
 { id: 1, name: 'Mango Frozen', price: '$4', category: 'Cold Drinks' },
  { id: 2, name: 'Strawberry Frozen', price: '$4', category: 'Cold Drinks' },
  { id: 3, name: 'Pineapple Frozen', price: '$4', category: 'Cold Drinks' },
  { id: 4, name: 'Mango & Strawberry', price: '$4', category: 'Cold Drinks' },
  { id: 5, name: 'Fresh Orange', price: '$3', category: 'Cold Drinks' },
  { id: 6, name: 'Lemonade', price: '$3', category: 'Cold Drinks' },
  { id: 7, name: 'Minted Lemonade', price: '$3.5', category: 'Cold Drinks' },
  { id: 8, name: 'Apple', price: '$3', category: 'Cold Drinks' },
  { id: 9, name: 'Passion Fruit', price: '$3', category: 'Cold Drinks' },
  { id: 10, name: 'Mocha Frappe', price: '$5', category: 'Cold Drinks' },
  { id: 11, name: 'Orea Milkshake', price: '$5', category: 'Cold Drinks' },
  { id: 12, name: 'Iced Coffee', price: '$3.5', category: 'Cold Drinks' },
  { id: 13, name: 'Iced Latte', price: '$4', category: 'Cold Drinks' },
  { id: 14, name: 'Chocolate Cake', price: '$6', category: 'Cold Drinks' },
  { id: 15, name: 'Iced Mocha', price: '$3.5', category: 'Cold Drinks' },
  { id: 16, name: 'Peach Iced Tea', price: '$3.5', category: 'Cold Drinks' },
  { id: 17, name: 'Laziza', price: '$3', category: 'Cold Drinks' },
  { id: 18, name: 'Mexican Laziza', price: '$3.5', category: 'Cold Drinks' },
  { id: 19, name: 'Boom Boom', price: '$3.5', category: 'Cold Drinks' },
  { id: 20, name: 'Dark Blue', price: '$3', category: 'Cold Drinks' },
  { id: 21, name: 'Red Bull', price: '$5', category: 'Cold Drinks' },
  { id: 22, name: 'Freez', price: '$3', category: 'Cold Drinks' },
  { id: 23, name: 'Mr.Juicy', price: '$0.5', category: 'Cold Drinks' },
  { id: 24, name: 'Pepsi', price: '$2', category: 'Cold Drinks' },
  { id: 25, name: 'Mirinda', price: '$2', category: 'Cold Drinks' },
  { id: 26, name: '7Up', price: '$2', category: 'Cold Drinks' },
  { id: 27, name: 'Water(Small)', price: '$1', category: 'Cold Drinks' },
  { id: 28, name: 'Water(Big)', price: '$2', category: 'Cold Drinks' },
  { id: 29, name: '+ Grenadine', price: '$0.5', category: 'Cold Drinks' },
  { id: 30, name: 'Tea', price: '$1.5', category: 'Hot Drinks' },
  { id: 31, name: 'Coffee', price: '$1.5', category: 'Hot Drinks' },
  { id: 32, name: 'Nescafe', price: '$3', category: 'Hot Drinks' },
  { id: 33, name: 'Nescafe 3in1', price: '$3', category: 'Hot Drinks' },
  { id: 34, name: 'Nescafe 2in1', price: '$3', category:'Hot Drinks' },
  { id: 35, name: 'Cappucino', price: '$3.5', category: 'Hot Drinks' },
  { id: 36, name: 'Hot Chocolate', price: '$3.5', category: 'Hot Drinks' },
  { id: 37, name: 'Latte', price: '$4', category: 'Hot Drinks' },
  { id: 38, name: 'Zhurat', price: '$1.5', category: 'Hot Drinks' },
  { id: 39, name: 'Zhurat (Cumin&Lemon)', price: '$1.5', category: 'Hot Drinks' },
  { id: 40, name: 'Sahlab', price: '$2', category: 'Hot Drinks' },
  { id: 41, name: 'Le Ciel Cocktail', price: '$7', category: 'Alcohol' },
  { id: 42, name: 'Vodka', price: '$5', category: 'Alcohol' },
  { id: 43, name: 'Passion Fruit', price: '$5', category: 'Alcohol' },
  { id: 44, name: 'Jamaica', price: '$6', category: 'Alcohol' },
  { id: 45, name: 'Mojito', price: '$6', category: 'Alcohol' },
  { id: 46, name: 'Baileys', price: '$6', category: 'Alcohol' },
  { id: 47, name: 'Whiskey Black', price: '$6', category: 'Alcohol' },
  { id: 48, name: 'Whiskey Chivas', price: '$6', category: 'Alcohol' },
  { id: 49, name: 'Whiskey Red Label', price: '$5', category: 'Alcohol' },
  { id: 50, name: 'Gin Basil', price: '6', category: 'Alcohol' },
  { id: 51, name: 'Watermelon Gin', price: '$6', category: 'Alcohol' },
  { id: 52, name: 'Strawberry smash', price: '$6', category: 'Alcohol' },
  { id: 53, name: 'Almaza', price: '$3', category: 'Alcohol' },
  { id: 54, name: 'Mexican Almaza', price: '$3.5', category: 'Alcohol' },
  { id: 55, name: 'Tequila sunrise', price: '$6', category: 'Alcohol' },
  { id: 56, name: 'Margarita', price: '$6', category: 'Alcohol' },
  { id: 57, name: 'Sex on the beach', price: '$6', category: 'Alcohol' },
   { id: 58, name: 'Shots', price: '$3.5', category: 'Alcohol' },
  { id: 59, name: 'Cheese', price: '$3.5', category: 'Sajj' },
  { id: 60, name: 'kafta', price: '$4.5', category: 'Sajj' },
  { id: 61, name: 'Zaatar', price: '$1.5', category: 'Sajj' },
  { id: 62, name: 'Keshek', price: '$3', category: 'Sajj' },
  { id: 63, name: 'Cocktail', price: '$3', category: 'Sajj' },
  { id: 64, name: 'Banadura & Basal', price: '$3', category: 'Sajj' },
  { id: 65, name: 'Labneh', price: '$2.5', category: 'Sajj' },
  { id: 66, name: 'Labneh & Zaatar', price: '$3', category: 'Sajj' },
  { id: 67, name: 'Martadilla & Ashawen', price: '$4', category: 'Sajj' },
  { id:  68, name: 'Habash & Ashawen', price: '$4', category: 'Sajj' },
  { id: 69, name: 'Nutella', price: '$5', category: 'Sajj' },
  { id: 70, name: '+ Cheese', price: '$0.5', category: 'Sajj' },
  { id: 71, name: '+ Vegetables', price: '$0.5', category: 'Sajj' },
  { id: 72, name: 'Lebanese Burger', price: '$7', category: 'Sandwiches' },
  { id: 73, name: 'Crispy', price: '$6', category: 'Sandwiches' },
  { id: 74, name: 'Tawouk', price: '$6', category: 'Sandwiches' },
  { id: 75, name: 'Batata', price: '$4', category: 'Sandwiches' },
  { id: 76, name: 'Lebanese Burger Plate', price: '$8', category: 'Plates' },
  { id: 77, name: 'Crispy Plate', price: '$8', category: 'Plates' },
  { id: 78, name: 'Tawouk Plate', price: '$8', category: 'Plates' },
  { id: 79, name: 'Batata Plate', price: '$3', category: 'Plates' },
  { id: 80, name: 'Nuts', price: '$2', category: 'Crackers' },
  { id: 81, name: 'Carrots', price: '$2', category: 'Crackers' },
  { id: 82, name: 'Chinese Nuts', price: '$2', category: 'Crackers' },
  { id: 83, name: 'Tormos', price: '$2', category: 'Crackers' },
  { id: 84, name: 'Rez b Halib', price: '$3.5', category: 'Desserts' },
  { id: 85, name: 'Jello', price: '$2.5', category: 'Desserts' },
  { id: 86, name: 'Castard', price: '$3.5', category: 'Desserts' },
  { id: 87, name: 'Tefeh', price: '$6', category: 'Shisha' },
  { id: 88, name: 'Tefeh Nakhli', price: '$5', category: 'Shisha' },
  { id: 89, name: 'Grape & Mint', price: '$5', category: 'Shisha' },
  { id: 90, name: 'Ajami', price: '$7', category: 'Shisha' },
  { id: 91, name: 'Nak-ha', price: '$7', category: 'Shisha' },
  { id: 92, name: 'Tefeh head change', price: '$3', category: 'Shisha' },
  { id: 93, name: 'Ajami head change', price: '$3.5', category:'Shisha' },
  { id: 94, name: 'Plastic Nabrish', price: '$1.5', category: 'Shisha' },
 
];
